### PR TITLE
Hypervisor framework compability for QEMU driver with --qemu-hvf flag

### PR DESCRIPTION
**Pull request by leonsmith**
Add in Hypervisor framework compability for QEMU driver with --qemu-hvf flag

### CODE REVIEW

**Comment by leonsmith** [comment]
This resolved #10 but without adding in a new driver thanks to @tonyjames comments

**Comment by sycured** [comment]
I tried your patch but it's not working… Compiled using master + your diff

1st try: `podman-machine create --driver qemu` : no automatic detection… ok
2nd try: `podman-machine create --driver qemu --qemu-hvf` : `flag provided but not defined: -qemu-hvf`

**Comment by sanshirookazaki** [comment]
Hi @sycured  It worked on my mac.
```podman-machine create box --driver qemu --qemu-hvf```

Can you see ```--qemu-hvf``` flag in the help text?
```podman-machine create --driver qemu -h | grep qemu-hvf```

**Comment by sycured** [comment]
@sanshirookazaki no HVF on help output

**Comment by sanshirookazaki** [comment]
@sycured 
The built binary might not be in your path.
On my mac, it worked with the steps below
```
$ make
$ mv podman-machine /usr/local/bin/podman-machine
$ podman-machine create box --driver qemu --qemu-hvf
```

**Comment by sycured** [comment]
I did with ./podman-machine

**Comment by afbjorklund** [comment]
Sorry for leaving this up unattended

**Pull request merged**
